### ISSUE TITLE
Error on pub serve

### ISSUE THREAD

**Issue by adaojunior** [matthewfranglen/dart-jsonp#1]
I'm getting an error when running `pub serve`

```
C:\tools\dart-sdk\bin\pub.bat serve web --port=50884
Loading source assets...
Error on line 10, column 3 of C:\Users\MY_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\jsonp-1.0.4\pubspec.yaml: Error loading transformer "polymer": package "polymer" is not a dependency.
- polymer:
  ^^^^^^^
Pub Serve terminated
```

Seems like the polymer library is not really necessary since it is only used in the examples.

**Comment by matthewfranglen** [comment]
Thanks for the bug report. I will look into this.

**Comment by adaojunior** [comment]
I think it is a good idea to remove the Polymer dependency. And maybe keep the example as simple as possible since most people won't care about it as long as they have a good documentation.

**Comment by matthewfranglen** [comment]
Can you try using 1.0.6

**Comment by adaojunior** [comment]
Yes, it is working now.

**Comment by matthewfranglen** [comment]
Great stuff.
