### ISSUE TITLE
Strong mode

### ISSUE THREAD

**Issue by jodinathan** [matthewfranglen/dart-jsonp#3]
Hi,

There are 3 or 4 errors when using with strong mode.
I fixed it locally, but can't seem to send a pull request.

**Comment by matthewfranglen** [comment]
I can't see the changes on your fork. Perhaps you have forgotten to push them?

**Comment by jodinathan** [comment]
Done it. The commit button was disabled before, dunno why.

https://github.com/matthewfranglen/dart-jsonp/pull/4

I did some minor tests and seems ok, I will test more later to use in production.

**Comment by matthewfranglen** [comment]
Thank you for the PR. I am looking into it now.

**Comment by matthewfranglen** [comment]
I have merged the code that addresses this issue. I will release a new version and then close this.

**Comment by matthewfranglen** [comment]
I have released https://github.com/matthewfranglen/dart-jsonp/releases/tag/2.1.0 to pub. Hopefully the docs will build soon.

I think this issue is resolved. Thanks for taking the time to do this.
